[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/Using Data Micro Course (interactive).dc.html"
  status = 200

[[redirects]]
  from = "/verify"
  to = "/Verify.dc.html"
  status = 200
